// import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { Navbar } from "@/components/general/navbar";
import { Footer } from "@/components/general/footer";

const open_sans = Open_Sans({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
