// import type { Metadata } from "next";
// import { Open_Sans } from "next/font/google";
// import "./globals.css";
// import { Navbar } from "@/components/general/navbar";

// const open_sans = Open_Sans({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${open_sans.className}bg-[radial-gradient(ellipse_at_top,var(--tw-gradient-stops))] from-[#fff] to-[#f5f5f5]`} >
//         <Navbar />
//         <>
//           {children}
//         </>
//         </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/general/navbar";
import { SessionProvider } from "next-auth/react";

const open_sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${open_sans.className} bg-[radial-gradient(ellipse_at_top,var(--tw-gradient-stops))] from-[#fff] to-[#f5f5f5]`}>
        <SessionProvider>
          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}


